version: 0.2

env:
  parameter-store:
    DB_NAME: "/HC/DJNAGO/RDS_DATABASE"
    DB_HOST: "/HC/DJNAGO/RDS_ENDPOINT"
    DB_PASS: "/HC/DJNAGO/RDS_PASSWORD"
    DB_USER: "/HC/DJNAGO/RDS_USER"
    DB_PORT: "/HC/DJNAGO/RDS_PORT"

phases:
  build:
    commands:
      - echo "Creating environment file..."
      - echo "DB_NAME=$DB_NAME" > .env
      - echo "DB_HOST=$DB_HOST" >> .env
      - echo "DB_PASS=$DB_PASS" >> .env
      - echo "DB_USER=$DB_USER" >> .env
      - echo "DB_PORT=$DB_PORT" >> .env
      - echo "Making deployment scripts executable..."
      - chmod +x scripts/*.sh
      - echo "Checking deployment files..."
      - ls -la
      - ls -la scripts/

artifacts:
  files:
    - '**/*'
